#!/bin/bash

set -e

source "$HOME/.rvm/scripts/rvm"

if [[ "$LIBSSL" == "1.0" ]]; then
  sudo apt install libssl1.0-dev
  rvm use --install $RB --autolibs=read --disable-binary
elif [[ "$LIBSSL" == "1.1" ]]; then
  rvm use --install $RB --binary --fuzzy
fi

[[ "`ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'`" =~ "OpenSSL $LIBSSL" ]] || { echo "Wrong libssl version"; exit 1; }

gem install bundler -v 2.1.4
rm Gemfile.lock
